config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

    resources :sessions
    resources :drinks
    resources :users do
    resources :consumptions
    end

end

app/models/consumption.rb
class Consumption < ActiveRecord::Base
  belongs_to :user
  belongs_to :drink 

 def self.calculate_bag(user)
    num_of_units = user.drinks.count
    weight = user.weight
    if user.sex == true
        sex = 0.61
      else 
        sex = 0.72
      end
    time = ((Time.now - user.drinks.first.created_at) / 60) / 60
    bac = (num_of_units * 10) / (weight * sex) - (time - 0.5) * (weight * 0.002)
    if bac < 0 
       bac = 0
    end 

    return bac
 end

 def self.drunk_level(bac) 
   if bac < 0.3
    "Drink up mate"
   elsif bac > 0.2 && bac < 0.5
    "You're getting there"
   elsif bac > 0.5 && bac < 0.9
    "Heals in the seeling"
   elsif bac > 0.9 && bac < 1
    "The first one to oblivian wins!!!"
   elsif bac >1 && bac < 2
    'Piss ass drunk'
   else  bac > 2 && bac > 2.5
    "You're just shit faced!"
  end
 end

 def self.drive(bac)
  if bac < 0.5
    "you can drive"
  else 
    "DO NOT DRIVE, YOU HAD ONE TO MANY"
  end
end

def self.calculate_calories(user)
    total_calories = user.drinks.map(&:calories).inject(:+)
end

# def show_name
#  @drinks.where(name:"beer")
# end
end


  
  

app/models/drink.rb
class Drink < ActiveRecord::Base
  has_many :consumptions
  has_many :drinks, through: :consumption
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :consumptions
  has_many :drinks, through: :consumptions

  # has_secure_password
  # validates :password, presence: true, on: :create
  # validates :email, presence: true
  # validates :email, uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  # private 

  #  def current_user
  #   begin 
  #     @current_user ||=User.find(session[:user_id]) if session[:user_id]
  #   rescue ActiveRecord::RecordNotFound
  #     session[:user_id] = nil
  #   end
  # end

end

app/controllers/consumptions_controller.rb
class ConsumptionsController < ApplicationController
  
  def index
    @user = User.find(params[:user_id])
    @bac  = Consumption.calculate_bag(@user)
    @totalcalories = Consumption.calculate_calories(@user)
    
    @consumption = Consumption.new 
    drinks_count =  @user.drinks.count
    @user = User.find(params[:user_id])
    @drunkLevel = Consumption.drunk_level(@bac)
    @drive = Consumption.drive(@bac)
    # name per drink
    drink_beer = @user.drinks.all.where(name:"Beer").count
    drink_wine = @user.drinks.all.where(name:"Wine").count
    drink_spirit = @user.drinks.all.where(name:"Spirit").count
    drink_shot = @user.drinks.all.where(name:"Shot").count
    
    # for ajax request right away on the page
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: {bac: @bac, drinks_count: drinks_count, totalcalories: @totalcalories, drink_beer: drink_beer, drink_wine: drink_wine, drink_spirit: drink_spirit, drink_shot: drink_shot, } }
    end

  end

  def new
    @consumption = Consumption.new 
    @user = User.find(params[:user_id])
  end

  def create

   @user = User.find(params[:user_id])
   consumption = Consumption.create(drink_id: params[:consumption][:drink], user_id: params[:user_id])
   @bac  = Consumption.calculate_bag(@user)
   drink_name = consumption.drink.name
   drinks_count =  @user.drinks.count
   drinks_calories =  Consumption.calculate_calories(@user)
   drinks_bac =  Consumption.calculate_bag(@user)
   drunk_level = Consumption.drunk_level(@bac)
   drive = Consumption.drive(@bac)
   drink_beer = @user.drinks.all.where(name:"Beer").count
   drink_wine = @user.drinks.all.where(name:"Wine").count
   drink_spirit = @user.drinks.all.where(name:"Spirit").count
   drink_shot = @user.drinks.all.where(name:"Shot").count
    
    # ajax create 
  respond_to do |format|
    if consumption.save
      format.html { redirect_to user_consumptions_path } 
      format.json { render json: {drink_name: drink_name, drinks_count: drinks_count, drinks_calories: drinks_calories, drinks_bac: drinks_bac, drunk_level: drunk_level, drive: drive, drink_beer: drink_beer, drink_wine: drink_wine, drink_spirit: drink_spirit, drink_shot: drink_shot},   status: :created }
    else
      format.html { render action: "new" }
      format.json { render json: consumption.errors, status: :unprocessable_entity }
    end
  end

  
  end

  def destroy
    #ajax delete
    consumption = Consumption.find(params[:id])
    consumption.destroy
    
    respond_to do |format|
      format.html  
      format.json { render json: { head: :no_content } }
    end
  end

  def show  
    @consumption = Consumption.find(params[:id])
  end 


end

 

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
    @drinks = Drink.all
  end

  def new 
    @drink = Drink.new
  end

  def create
    @drink = Drink.new(drinks_params)
  end

  private
    def drinks_params
      params.require(:drink).permit(:drink_id) 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def new
  # end
 
  # def create
  #   user = User.where(email: params[:email]).first
 
  #   if user && user.authenticate(params[:password])
  #     session[:user_id] = user.id
  #     redirect_to root_url, notice: "Logged in!"
  #   else
  #     flash.now.alert = "Invalid email or password"
  #     render "new"
  #   end
  # end
 
  # def destroy
  #   session[:user_id] = nil
  #   redirect_to root_url, notice: "Logged out!"
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  # def new
  #   @user = User.new
  # end

  # def create 
  #   @user = User.new(params.require(:user).permit(:name, :email, :password, :password_conformation))

  #   if @user.save
  #     redirect_to root_path, notice: 'signed up!'
  #   else
  #     render 'new'
  #   end
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/consumptions/index.html.erb
<div class="container">
<!-- <div class="head">YOUR PERSONAL ALCOHOL TRACKER </div> -->

  <div class="box-container">

    <div class="box col-3 one margin-right">
      <div class="box-title">
        COUNT
        <div class="sub-heading" id="calulate-bac"></div>  
      </div>
      <p class="description">BLOOD ALCOHOL LEVEL</p>
    </div>

    <div class="box col-3 two">
      <div class="box-title">
        <%= @user.name %> ALCOHOL TRACKER
       <!--  <div class="sub-heading"></div> -->
        <button class="userinfo">INFO</button>
      </div>
    </div>

    <div class="box col-3 margin-left three">
      <div class="box-title">
        AMOUNT 
      <div class="sub-heading" id="calulate-calories"></div>
     </div>
      <p class="description">TOTAL CALORIES BOOZED</p>
    </div>
  </div>

  <div  class="box"id="usertoggle">
    <div>
      USERS INFO
      <div class="box-1">
        <h2 class="">Name:</h2>
        <div class="sub-heading"><%= @user.name %></div>
      </div>
      <div class="box-1">
        <h2 class="">Height:</h2>
        <div class="sub-heading"><%= @user.height %></div>
      </div>
      <div class="box-1">
        <h2 class="">Weight:</h2>
        <div class="sub-heading"><%= @user.weight %></div>
      </div>
      <div class="box-1">
        <h2 class="">Age:</h2>
        <div class="sub-heading"><%= @user.age %></div>
      </div>
    </div>
  </div>

  <div class="box-container">

  <div class="box col-4 black four">
      <div class="box-title">
        AMOUNT
        <div class="sub-heading" id="drink-count"></div>
      </div>
      <p class="description-right">YOUR TOTAL SCORE</p>
    </div>

    <div class="box col-4 white five">
      <div class="box-title" id="drink_form">
        ADD A DRINK
        <button id="add_drink">ADD DRINK</button>
     </div>
    </div>
     
     <div class="box col-4 black box-title six">
      <div id= "drunk-level"></div>
      <p class="description-special">LEVEL OF DRUNKNESS</p>
    </div>
  

    <div class="box col-4 white change seven" >
      <div class="box-title" id="drink-list">
        GET SOBER 
        <div><button class="drinkinfo">LIST</button></div>
      </div>
    </div>
  </div>

  <div class="box box-title" id="drinktoggle">
    <% @user.consumptions.each do |consumption| %>
      <ul id="deletedrinklist">
        <li><%= consumption.drink.name %></li>
        <button id="destroy" data-id="<%= consumption.id %>">Delete</button>
      </ul>
    <% end %> 
  </div>

  <div class="box-container">
    <div class="box" id="adddrinktoggle">
      <div class="box-title add-drink">
        What did you drink?
        <%= form_for [@user, @consumption] do |f| %>
          <%= f.collection_select(:drink, Drink.all, :id, :name) %>
          <%= f.submit %>
        <% end %>  
        <button id="add_drink">ADD DRINK</button>
      </div>
    </div>
  </div>
  
  <div class="box-container" >
   
    <div class="box bg-cink col-5 box-title eight" id="hallo"></div>
       
    <div class="box col-5 nine">
      <div class="box-4">
        <h2 class="">BEERS</h2>
        <div class="title-drink" id="beer"></div>
      </div>
      <div class="box-4">
        <h2>WINE</h2>
        <div class="title-drink" id="wine"></div>
      </div>
      <div class="box-4">
        <h2>SPIRITS</h2>
        <div class="title-drink" id="spirit"></div>
      </div>
      <div class="box-4">
        <h2>SHOT </h2>
        <div class="title-drink sub-heading" id="shot"></div>
      </div>
    </div>
      
    <div class="box col-5 ten ">
      <div class="box-title" id="drive"></div>
    </div>
  </div>
</div>

<!-- <div class="flip-container" ontouchstart="this.classList.toggle('hover');">

  <div class="flipper">
    <div class="front">
      hello
    </div>
    <div class="back">
      jkasdjfl
    </div>
  </div>
</div> -->

app/views/consumptions/new.html.erb
<h1>What did you drink?</h1>
<div id="drinkForm">
  <%= form_for [@user, @consumption] do |f| %>
    <%= f.collection_select(:drink, Drink.all, :id, :name) %>
    <%= f.submit %>
  <% end %>
</div>

app/views/consumptions/show.html.erb
<h2>this is the show page</h2>

app/views/drinks/index.html.erb
<h1>This is the drinks index page</h1>

  <%= link_to 'Add a drink', new_drink_path %>
  

app/views/drinks/new.html.erb
<h1>add a drink page</h1>



<%= collection_select(:user, :drink_id, Drink.all, :id, :name) %>

<button>add drink</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiaryAlcohol</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/users/index.html.erb
<h1>hello this is the index page</h1>